version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: barryvdh/laravel-debugbar
    versions:
    - 3.5.2
    - 3.5.4
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: spatie/laravel-permission
    versions:
    - 4.0.0
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: laravel/framework
    versions:
    - 6.20.11
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.2.0
